//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estados.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public int Id { get; set; }
        public int Municipio_Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CP { get; set; }
        public string Zona { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
